Yamato-Security/hayabusa

- README-English.md
- README-Japanese.md
スクリーンショットのリンクが壊れちゃったので直しました。
また、PDFをアップロードしました。
> fix image broken link and add PDFs

- Cargo.toml
closes #370
happened compile error in clap v3.
specified clap v2.x
> fixed clap library version specifed #370

- Cargo.toml
closes #370 
happened compile error in clap v3.
specified clap v2.x
> specified clap version specified #370

- README-English.md
- README-Japanese.md
> readme update

- Cargo.lock
- Cargo.toml
fast-allocを有効にしました。 closes #367.
> enabled fast-alloc

- .gitmodules
- README-Japanese.md
- README.md
- src/main.rs
- Changed rule repository update method from git clone and pull to git clone and submodule update
refs: https://github.com/Yamato-Security/hayabusa/pull/392#pullrequestreview-884677271
> Added update command#391 submodule ver

- config/level_color.txt
- src/afterfact.rs
英語的にUnique rulesよりも(上に合わせて）Unique Detectionsの方が自然なので、変えました。
また、レベルの色は緑が一番無難そうなので、それをlowにしました。
> unique rules to detections

- src/main.rs
Fixed #432 
- Add process when the .git folder is not exist in hayabusa folder.
> Hotfix/failed twice update rule#432

- README-Japanese.md
- README.md
closes #453 
-  BlackHat Asia 2022 Arsenal badge (temporary. if official badge released, need change.)
- Rust Report Card badge
- Repository Maintenance Levels badge
> Document/add badges#453

- src/detections/print.rs
- src/detections/rule/matchers.rs
- src/detections/rule/selectionnodes.rs
- src/detections/utils.rs
- src/filter.rs
closes #440 
TODO
* 後で下記ファイルを消す
* ./rules/config/regex/record_data_filter.txt
* ルールファイルのドキュメント修正
> Feature/#440 refactoring #395

- README-Japanese.md
- README.md
- src/detections/configs.rs
- src/filter.rs
Closed #456 
- Added `-C --config` option
> Enhancement: add config config #456

- README-Japanese.md
- README.md
- src/afterfact.rs
Fixed #382 
- added filtering control char in detail 
Checked output finished by following command In Windows Terminal.
``` powershell
PS > ./hayabusa.exe -d ./hayabusa-sample-evtx
```
> Fixed output stop when  control char exist in windows terminal

- src/detections/detection.rs
closes #477 
-  added reduce feature of output mitre attck tag to aggregation Condition rule.
> reduce output mitre attck agg cond details tactic no to aggregation condition

- README-Japanese.md
- README.md
- src/detections/detection.rs
closes #519 
- added twitter badge and link
- added link to rust reportcard
- added link to release
> added twitter badge and link #519

- Cargo.lock
- Cargo.toml
- README-Japanese.md
- README.md
- src/detections/configs.rs
- src/detections/detection.rs
- src/detections/print.rs
- src/lib.rs
- src/main.rs
- src/timeline/statistics.rs
- src/timeline/timelines.rs
・developerベースにログイン成功・失敗の集計結果出力を実装しました。
・pretteytableを利用し、表形式に成形して出力させています。
・ログインイベントがない場合は、「No login event was detected.」と表示します。
・オプションは「-L」(大文字)としています。
・-dオプションの対応も確認しております。
ご確認をお願いいたします。
> logon summary #110

- src/detections/configs.rs
- src/detections/detection.rs
Closes #521 
- changed version 1.2.0 -> 1.2.1
````powershell
PS >.\hayabusa.exe --version
hayabusa 1.2.1
PS >.\hayabusa.exe -V       
hayabusa 1.2.1
```
> fixed version number #521

- Cargo.lock
- Cargo.toml
- src/afterfact.rs
Closes #533 
- added timeline histogram output
> output timeline histogram

- Cargo.lock
- README.md
- src/afterfact.rs
- src/detections/configs.rs
- src/main.rs
Closes #538
- added total events count.
- added datareduction count and percentage.
```powershell
PS >./hayabusa.exe -d .\hayabusa-sample-evtx\ -q --output 538.csv
```
> Display total event count and data reduction

- README-Japanese.md
- README.md
- config/profiles.txt
- updated document (slow at first runafter PC boot)
> updated document #355

- Cargo.lock
- Cargo.toml
regexを1.5.xから1.6.xにアップデート & `cargo update`しました。
> update regex 1.5 to 1.6

- README-Japanese.md
- README.md
細かい修正ですみません。
DownLoads -> Downloads
> Downloads typo fix

- .gitignore
- src/afterfact.rs
> change wording

- README-Japanese.md
- README.md
Closes #695 
- Added code blue 2022 blue-box badge
> Added code blue 2022 blue-box badge

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- README-Japanese.md
- README.md
- sample-results/README.md
失礼しました！`rustup update stable`だけではクロスコンパイル用のコンパイラが更新されないようで、`rustup install stable-i686-pc-windows-msvc`を実行したら、Windows 32bit用のコンパイラが1.60から1.64に更新されて、無事にコンパイルできました。
その注意事項をreadmeに追加しました。
> use evtx 0.8.3

- .gitignore
間違えてMetricsとログオン情報の`.txt`ファイルをアップロードしないように。
> ignore txt file uploads

- README-Japanese.md
- README.md
Readmeに色々誤りがあったので、修正しました。ご確認ください。
PDFも更新しておきたいので、マージはこちらでさせてください。
(修正のチェックが終わったら、PDF化して、それもアップロードします）
> update readme 2022-10-17

- README-Japanese.md
- README.md
関連プロジェクトを気づくところ（上の方）に載せた方が良いという指摘があったので、追加しました。
> add companion projects to readme

- .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
- CHANGELOG-Japanese.md
- CHANGELOG.md
- src/afterfact.rs
**What Changed**
- Changed Details field in JSON output to object
- Updated Changelog
- Updated pull request template
**Evidence**
<details>
<summary>Result</summary>
```
>./hayabusa.exe -f ..\hayabusa-sample-evtx\DeepBlueCLI\disablestop-eventlog.evtx -q --set-default-profile minimal -o 773.json -j
...
Elapsed time: 00:00:03.311
Saved file: 773.json (552 B)
PS >cat 773.json
{
"Timestamp": "2019-04-28 06:04:25.733 +09:00",
"Computer": "DESKTOP-JR78RLP",
"Channel": "Sys",
"EventID": 104,
"Level": "high",
"RuleTitle": "Log File Cleared",
"Details": {
"User": "jwrig"
}
}
{
"Timestamp": "2019-04-28 06:04:32.373 +09:00",
"Computer": "DESKTOP-JR78RLP",
"Channel": "Sys",
"EventID": 7040,
"Level": "med",
"RuleTitle": "Event Log Service Startup Type Changed To Disabled",
"Details": {
"OldSetting": …
```
> Changed Details field in JSON output to object

- README-Japanese.md
- README.md
> Fix Krb typo

- README-Japanese.md
- README.md
update readme mitre file name. (output_tag.txt -> mitre_tactics.txt)
> fix readme mitre_tactics.txt file name

- src/debug/checkpoint_process_timer.rs
- Raised code coverage percentage in debug
> Enhancement: raise code coverage percentage in debug

- Cargo.lock
- Cargo.toml
- README-Japanese.md
- README.md
- src/detections/configs.rs
ソースコードで`2.0.0`を`2.1.0`への更新、Readmeの更新等忘れたので、更新しておきました。
> Finalize 2.1.0 (again)

- README-Japanese.md
- README.md
- Added SECCON badge
- updated rules
> Add seccon 2023 shield

- Cargo.lock
- Cargo.toml
I updated evtx crate to the hayabusa-evtx 0.8.4 one.
> update to hayabusa-evtx-0.8.4

- .github/workflows/integration-test.yml
The GitHub Actions Integration test did not support the latest command specifications, so I fixed it.
I would appreciate it if you could review🙏
> Fixed broken GitHub Actions Integration test

- Cargo.lock
- src/detections/utils.rs
> remove debug output info

- README-Japanese.md
- README.md
added MaxMind link to license section
> added MaxMind link to license section

- CHANGELOG-Japanese.md
- CHANGELOG.md
- Cargo.lock
- Cargo.toml
> update evtx crate

- CHANGELOG-Japanese.md
- CHANGELOG.md
- src/timeline/timelines.rs
- Added first and last timestamp to output in metrics command with directory option.
<details>
<summary>main</summary>
```
>.\main.exe metrics -d ../hayabusa-sample-evtx -q
Generating Event ID Metrics
...
Analyzing event files: 584
Total file size: 137.1 MB
584 / 584 [==========================================================================] 100.00 %
Total Event Records: 47471
╭───────┬─────────┬─────────────────────────────────────────┬───────┬────────────────────────────────────────────────────────────────────────────────────────╮
│ Count ┆ Percent ┆ Channel                                 ┆ ID    ┆ Event
│
╞═══════╪═════════╪═════════════════════════════════════════╪═══════╪════════════════════════════════════════════════════════════════════════════════════════╡
│ 9714  ┆ 20.5%   ┆ …
```
> print first and last timestamp in metrics command when the target is a directory

- Cargo.lock
- Cargo.toml
updated the crates to use the latest.
> update crates 2023-03-15

- CHANGELOG-Japanese.md
- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- src/detections/configs.rs
- src/timeline/timelines.rs
I updated the logon-summary titles to make them more easy to understand.
> updated logon-summary titles

- doc/AnalysisWithJQ-English.md
- doc/AnalysisWithJQ-Japanese.md
I updated the JQ documentation. Could you check it whenever you get time?
> Add Powershell scriptblock extraction to jq docs

- CHANGELOG-Japanese.md
- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- src/detections/configs.rs
I would like to release the current version as 2.3.3.
Could you please check?
> finalize 2.3.3

- src/afterfact.rs
- src/detections/detection.rs
- src/detections/message.rs
- src/detections/utils.rs
- replaced trim method in afterfact with process in detection
> perf: replaced trim method in afterfact with process in detection

- CHANGELOG-Japanese.md
- CHANGELOG.md
- Cargo.lock
- src/main.rs
- replaced message and usage color green with white
> UI(main): fixed part of help menu green color #989

- .github/workflows/coverage.yml
- .github/workflows/rust.yml
> ci(rust/coverage): removed action-rs #994

- Cargo.lock
- Cargo.toml
- src/afterfact.rs
- src/detections/configs.rs
I will be busy in Korea from tomorrow so I would like to finalize 2.4.0 as it is now.
Could you please check?
By the way, I changed "Event Frequency Timeline" to "Detection Frequency Timeline" because the timeline is of what was detected and not the original events (including events w/o detections). 
"Event Frequency Timeline" could be confused as showing all of the original events.
> finalize 2.4.0

- src/detections/configs.rs
- src/main.rs
- src/timeline/search.rs
- src/timeline/timelines.rs
- Changed the help menu to output when the condition is not satisfied by the search command
- Changed the search command to output the result in red color when there are zero detections.
> fixed UI in Search Command

- CHANGELOG-Japanese.md
- CHANGELOG.md
- src/detections/configs.rs
- src/timeline/search.rs
- added multiline output to search command
- main branch output( `-M` option  does not exist in search command on main branch)
```
PS > ./main.exe search -d ..\hayabusa-sample-evtx\ --keywords "null" -o main.csv
...
Total event log files: 584
Total file size: 137.1 MB
584 / 584 [==========================================================================] 100.00 %
Total findings: 44144
Elapsed time: 00:00:09.375
```
- This PR
```
> ./1004.exe search -d ..\hayabusa-sample-evtx\ --keywords "null" -o 1004.csv -M
...
Total event log files: 584
Total file size: 137.1 MB
584 / 584 [==========================================================================] 100.00 %
Total findings: 44144
Elapsed time: 00:00:09.570
```
- main branch output
```
PS >cat main.csv | select-object -First 2 …
```
> Added multiline output to search command

- CHANGELOG-Japanese.md
- CHANGELOG.md
- src/afterfact.rs
- Fixed bug info alert shows up twice in results summary
- main
```
>./main.exe csv-timeline -d ../hayabusa-sample-evtx -r rules/hayabusa/builtin/BitsClient_Op/BitsCli_59_Info_BitsJobCreated.yml
...
Events with hits / Total events: 168 / 47,459 (Data reduction: 47,291 events (99.65%))
Total | Unique detections: 168 | 1
Total | Unique critical detections: 0 (0.00%) | 0 (0.00%)
Total | Unique high detections: 0 (0.00%) | 0 (0.00%)
Total | Unique medium detections: 0 (0.00%) | 0 (0.00%)
Total | Unique low detections: 0 (0.00%) | 0 (0.00%)
Total | Unique informational detections: 168 (100.00%) | 1 (100.00%)
Dates with most total detections:
critical: n/a, high: n/a, medium: n/a, low: n/a, informational: 2020-11-12 (20)
Top 5 computers with most unique detections:
critical: n/a
high: n/a …
```
> Fixed bug info alert shows up twice in results summary

- README-Japanese.md
- README.md
- Added SANS DFIR Summit badge Add SANS DFIR Summit 2023
I would appreciate it if you could review when you have time
> docs(README): added SANS DFIR Summit badge Add SANS DFIR Summit 2023 badge

- doc/TimesketchImport/TimesketchImport-English.md
- doc/TimesketchImport/TimesketchImport-Japanese.md
- Add Timesketch instructions for v2
> 📚 Add Timesketch instructions for v2

- CHANGELOG-Japanese.md
- CHANGELOG.md
- src/afterfact.rs
- src/detections/message.rs
- src/main.rs
- Reverted MESSAGEKEYS DashMap to HashMap
> 1088 speed up results summary calculation

- CHANGELOG-Japanese.md
- CHANGELOG.md
- src/afterfact.rs
- Fixed some fields are moved over in json output
> Fixed some fields are moved over in json output

- README-Japanese.md
- README.md
There was a minor typo in the metrics command example, so I fixed it :)
> fix: README modify metrics command example

- CHANGELOG-Japanese.md
- CHANGELOG.md
- src/detections/configs.rs
- src/main.rs
- src/timeline/metrics.rs
- src/timeline/timelines.rs
- renamed `metrics` command `eid-metrics`
> renamed `metrics` command `eid-metrics`

- CHANGELOG-Japanese.md
- CHANGELOG.md
- src/detections/configs.rs
- src/main.rs
- Renamed `--live_analysis` option with `--live-analysis`
> Renamed `--live_analysis` option with `--live-analysis`

- CHANGELOG-Japanese.md
- CHANGELOG.md
- src/main.rs
Closes https://github.com/Yamato-Security/hayabusa/issues/1143
Could you check this whenever you have time?
> Update progress bar

- CHANGELOG-Japanese.md
- CHANGELOG.md
- src/detections/configs.rs
- src/main.rs
- src/timeline/timelines.rs
- Added `--timeline-start` and `--timeline-end` to `logon-summary` command.
>  Added `--timeline-start` and `--timeline-end` to `logon-summary` command.

- CHANGELOG-Japanese.md
- CHANGELOG.md
- src/detections/configs.rs
- src/timeline/search.rs
- added and-logic option in search command #1162 
> added `--and-logic` to keyword  in `search` option

- CHANGELOG-Japanese.md
- CHANGELOG.md
- src/afterfact.rs
- src/detections/detection.rs
- src/detections/rule/condition_parser.rs
- src/detections/rule/count.rs
- src/detections/rule/matchers.rs
- src/detections/rule/mod.rs
- src/detections/rule/selectionnodes.rs
- src/detections/utils.rs
- src/main.rs
- src/options/profile.rs
- src/timeline/metrics.rs
- src/timeline/timelines.rs
- added `RecoveredRecord` column to the output profile
> added `RecoveredRecord` column to the output profile

- Cargo.lock
- Cargo.toml
- src/afterfact.rs
- src/detections/detection.rs
- src/detections/field_data_map.rs
- src/detections/message.rs
- src/detections/rule/count.rs
- src/detections/rule/matchers.rs
- src/detections/rule/mod.rs
- src/detections/rule/selectionnodes.rs
- src/detections/utils.rs
- src/main.rs
- src/timeline/computer_metrics.rs
- src/timeline/metrics.rs
- src/timeline/timelines.rs
- Cargo update
- Remove deprecated chrono function use
> Remove deprecated chrono function use

- CHANGELOG-Japanese.md
- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- README-Japanese.md
- README.md
- src/detections/configs.rs
I updated the readme and a few other things for 2.8.0.
Please check whenever you have time.
> finalize 2.8.0

- Cargo.lock
- src/afterfact.rs
- src/detections/configs.rs
- src/detections/detection.rs
- src/detections/message.rs
> crate update

- .github/workflows/integration-test.yml
Changed the integration-test command to use the following -w option.
- https://github.com/Yamato-Security/hayabusa/pull/1191
I would appreciate it if you could review when you have time🙏
> fix: Update GitHub Actions for Integration test

- CHANGELOG-Japanese.md
- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- src/detections/configs.rs
I updated the version info and crates for the release tomorrow.
> finalize 2.10.0

- CHANGELOG-Japanese.md
- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- README-Japanese.md
- README.md
- contributors.txt
- src/detections/configs.rs
- src/main.rs
I want to release this as a minor fix due to important bug fixes. I called it the "kamemushi tsubushi" release as there were lots of kamemushi in Japan this year. =)
> finalize 2.10.1

- CHANGELOG-Japanese.md
- CHANGELOG.md
- config/html_report/hayabusa_report.css
- config/mitre_tactics.txt
- src/afterfact.rs
- src/detections/detection.rs
- src/detections/message.rs
- add mitre tactics info to html report
> add mitre tactics info to html report

- src/detections/rule/condition_parser.rs
I reduced the number of AndContainer and OrContainer instance that Hayabusa creates when parsing condition section of rule files. 
* The previous logic creates unnecessary AndContainer. For example, if the condition section is `section1 and section2 and secion3 and section4`, previous logic creates three AndContainer like `AndContainer.(section1, AndContainer.(section2, AndContainer.(section3, secion4)))`. Current logic create only 1 AndContainer like `AndContainer.(section1, section2, section3, section4)` if the condition section is `section1 and section2 and secion3 and section4`.
* The previous logic creates OrContainer even if there is only one subtoken. For example, if the condition section is `section1 `, the previous logic creates OrContainer like `OrContainer(section1)`. The …
> reduce the number of AndContainer's and OrContainer's instance

- src/detections/rule/matchers.rs
- src/detections/rule/mod.rs
- src/detections/rule/selectionnodes.rs
I removed unnecessary unsafe block.
> Remove unneccesary unsafe block

- README-Japanese.md
- README.md
- src/detections/configs.rs
- added Bsides Tokyo 2024 badge
> added Bsides Tokyo 2024 badge #1289

- README-Japanese.md
- README.md
> fixed BSides typo

- Cargo.lock
- src/debug/checkpoint_process_timer.rs
- src/detections/configs.rs
- Fixed compile warnings due to chrono crate update
> Fixed compile warnings due to chrono crate update

- CHANGELOG-Japanese.md
- CHANGELOG.md
- src/detections/rule/matchers.rs
- src/detections/rule/mod.rs
- Added for support for `windash` keyword.
passed added test for `contains|windash` and `contains|all|windash` modifier.
I would appreciate it if you could check it out when you have time.
> Added support `windash` pipe modifier

- README-Japanese.md
- README.md
@hitenkoku 
I added a badge for total commits. Around 4000!
> add commits badge

- README-Japanese.md
- README.md
the total commits link was broken.
> fix commits link

- CHANGELOG-Japanese.md
- CHANGELOG.md
- src/detections/rule/correlation_parser.rs
- Closed #1338 
- Limitations of current implementation is same as https://github.com/Yamato-Security/hayabusa/pull/1357
> feat: add support for Sigma Correlation Value count

- CHANGELOG-Japanese.md
- CHANGELOG.md
- src/detections/rule/correlation_parser.rs
- src/detections/rule/mod.rs
- src/main.rs
> feat: Ignore referenced rules in correlation rules(when `generate: true` not set)

- CHANGELOG-Japanese.md
- CHANGELOG.md
- src/afterfact.rs
- src/detections/utils.rs
> chg: display `Data` field index string

- README-Japanese.md
- README.md
> added badge

- CHANGELOG-Japanese.md
- CHANGELOG.md
- Cargo.lock
- src/detections/detection.rs
- src/yaml.rs
- Closed #1374 
No difference in the result file compared to the main branch.
https://github.com/Yamato-Security/hayabusa/actions/runs/10035816024
All commands work properly.
https://github.com/Yamato-Security/hayabusa/actions/runs/10035814364
> fix: output correlation(and referenced) rule count

- CHANGELOG-Japanese.md
- CHANGELOG.md
- src/afterfact.rs
- #1383
```
hayabusa-2.16.1-win-x64.exe csv-timeline -l -w -m critical -q -o timeline.csv -C
Start time: 2024/08/12 16:49
Total event log files: 356
Total file size: 239.9 MB
Loading detection rules. Please wait.
Excluded rules: 4,266
Noisy rules: 12 (Disabled)
Deprecated rules: 14 (6.51%) (Disabled)
Experimental rules: 2 (0.93%)
Stable rules: 36 (16.74%)
Test rules: 177 (82.33%)
Unsupported rules: 2 (0.93%) (Disabled)
Hayabusa rules: 1
Sigma rules: 214
Total detection rules: 215
Creating the channel filter. Please wait.
Evtx files loaded after channel filter: 6
Detection rules enabled after channel filter: 104
Output profile: standard
Scanning in progress. Please wait.
[00:00:01] 6 / 6   [========================================] 100%
Scanning finished. Please wait while the results are …
```
> fix: Rule Author does not appear in the terminal

- README-Japanese.md
- README.md
> added SecTor Badge

- README-Japanese.md
- README.md
The -s option has been changed to sort-event in 2.17.0, so the README has been updated.
> doc: update --sort-events option description

- README-Japanese.md
- README.md
@fukusuket I added some 3rd party links to the readme. Could you update the Japanese readme whenver you have free time?
> add links to readme

- CHANGELOG-Japanese.md
- CHANGELOG.md
- LICENSE.txt
- README-Japanese.md
- README.md
I change the license to AGPL. Please check whenever you have time.
> change license to AGPL

- README-Japanese.md
- README.md
I fixed a typo and changed just a couple things
> Channel filtering typo

- README-Japanese.md
- README.md
Could you check this and add the Japanese documentation?
> add 2.18.0 documentation

- CHANGELOG-Japanese.md
- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- src/detections/configs.rs
- src/detections/detection.rs
- src/detections/field_data_map.rs
- src/detections/rule/condition_parser.rs
- src/detections/rule/correlation_parser.rs
- src/detections/rule/count.rs
- src/detections/rule/matchers.rs
- src/detections/rule/mod.rs
- src/detections/rule/selectionnodes.rs
- src/filter.rs
- src/main.rs
- src/options/profile.rs
- src/yaml.rs
closes https://github.com/Yamato-Security/hayabusa/issues/461
@fukusuket When you have time, could you check this?
> update to rust-yaml2

- CHANGELOG-Japanese.md
- CHANGELOG.md
- src/detections/configs.rs
- src/detections/rule/matchers.rs
- src/main.rs
- Closed #1440 
All commands completed successfully.
https://github.com/Yamato-Security/hayabusa/actions/runs/11637857776
> feat: load `windash` characters dynamically

- .github/workflows/coverage.yml
- .github/workflows/rust.yml
v3 actions are going to be deprecated soon so I updated to v4
> update actions to v4

- CHANGELOG-Japanese.md
- CHANGELOG.md
- Cargo.lock
- Cargo.toml
updated the hayabusa-evtx crate
> Update hayabusa evtx ver 0.8.12

- src/timeline/log_metrics.rs
- src/timeline/metrics.rs
- Closed #1494 
https://github.com/Yamato-Security/hayabusa/actions/runs/11820719366
> fix: invalid first/last timestamp in `log-metrics` command

- CHANGELOG-Japanese.md
- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- src/main.rs
- src/options/update.rs
- Closed #1492 
https://github.com/Yamato-Security/hayabusa/actions/runs/11818702742
> feat: add opening/closing messages

- src/main.rs
- Closed #1501 
- https://github.com/Yamato-Security/hayabusa/actions/runs/11923952190
> fix: restore stdout color

- CHANGELOG-Japanese.md
- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- src/detections/configs.rs
- src/main.rs
- src/options/update.rs
- Closed #1508 
- https://github.com/Yamato-Security/hayabusa/actions/runs/12010179021
> chg: not output progress bar when default timeline cmd option

- CHANGELOG-Japanese.md
- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- README.md
- src/detections/configs.rs
- src/main.rs
@fukusuket お待たせしました〜。 Could you check this and update the Japanese readme?
> Finalize 3.0.0

- CHANGELOG-Japanese.md
- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- src/detections/configs.rs
created this release to fix the expand parse rule check bug
> finalize 3.0.1

- CHANGELOG-Japanese.md
- CHANGELOG.md
Sorry, I forgot to update the date.
> fix changelog date

- Cargo.lock
- src/main.rs
- src/options/update.rs
- Closed #1556 
All test passed(include update-rules/update-rules with encoded_rules)
https://github.com/Yamato-Security/hayabusa/actions/runs/13052236964
> fix: compile error ureq v3

- CHANGELOG-Japanese.md
- CHANGELOG.md
- src/detections/configs.rs
- src/timeline/extract_base64.rs
-  Closed #1558 
https://github.com/Yamato-Security/hayabusa/actions/runs/13052625886
> feat: add PowerShellCore/Operational to extract-base64

- CHANGELOG-Japanese.md
- CHANGELOG.md
- src/detections/detection.rs
- Closed #1573 
https://github.com/Yamato-Security/hayabusa/actions/runs/13284161986
> fix: mitre tactics tag in json-timeline

- doc/TimelineExplorerAnalysis/TimelineExplorerAnalysis-English.md
- fix multiple spelling errors
> Timeline Explorer README - fix minor spelling errors

- README-Japanese.md
- README.md
@fukusuket I updated the `level-tuning` description. Could I ask you to update the JP version?
> update level-tuning doc

- CHANGELOG-Japanese.md
- CHANGELOG.md
- README-Japanese.md
- README.md
- src/timeline/extract_base64.rs
- Closed #1583 
https://github.com/Yamato-Security/hayabusa/actions/runs/13344764799
> feat: add system 7045 to extract-base64

- src/afterfact.rs
- Closed #1589 
https://github.com/Yamato-Security/hayabusa/actions/runs/13370505625
Sorry! I fixed it! I would appreciate it if you could check it out when you have time🙏
> fix: remove extra comma

- CHANGELOG-Japanese.md
- CHANGELOG.md
- src/afterfact.rs
- src/detections/configs.rs
- src/detections/detection.rs
- src/detections/rule/mod.rs
- src/main.rs
- src/options/htmlreport.rs
- src/timeline/search.rs
- src/timeline/timelines.rs
- Closed #1587
https://github.com/Yamato-Security/hayabusa/actions/runs/13371185405
> feat: add tab-seperator option in csv-timeline/search/log-metrics

- Cargo.lock
- Cargo.toml
- src/detections/configs.rs
@fukusuket I got everything ready for the 3.1.0 release. Please check when you have time.
> finalize 3.1.0

- CHANGELOG-Japanese.md
- CHANGELOG.md
- src/timeline/computer_metrics.rs
- src/timeline/metrics.rs
- src/timeline/timelines.rs
- Closed #1629 
https://github.com/Yamato-Security/hayabusa/actions/runs/13786971269
> feat: add OS information column to computer-metrics

- src/timeline/computer_metrics.rs
- Closed #1631 
https://github.com/Yamato-Security/hayabusa/actions/runs/13790810720
> chg: remove unneeded column

- CHANGELOG-Japanese.md
- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- src/detections/configs.rs
@fukusuket Thanks for all the last minute updates and fixes!
I finalized 3.1.1. Please check when you can.
> finalize 3.1.1

- Cargo.lock
- src/options/geoip_search.rs
- Closed #1645 
https://github.com/Yamato-Security/hayabusa/actions/runs/14150971591
> fix: maxmind crate compile error

- CHANGELOG-Japanese.md
- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- src/detections/configs.rs
Finalized for tomorrow's release
> finalize 3.2.0

- CHANGELOG-Japanese.md
- CHANGELOG.md
- src/timeline/computer_metrics.rs
- src/timeline/metrics.rs
- Closed #1656 
- https://github.com/Yamato-Security/hayabusa/actions/runs/14401513944
> feat: improve uptime in computer-metrics

- README-Japanese.md
- README.md
> fixed not valid a tag href

- CHANGELOG-Japanese.md
- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- src/detections/configs.rs
> finalize 3.3.0

- CHANGELOG-Japanese.md
- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- src/detections/configs.rs
- src/detections/message.rs
- src/timeline/search.rs
Closed #1627 
- default details abbreviations mapping to AllFieldInfo in search command result.
I don't believe my code contribution adds enough value to the project, so I would prefer not to be listed in contributes.txt or in any release acknowledgments. Thank you for your understanding.
> default details mapping to all field info handling in search result

- CHANGELOG-Japanese.md
- CHANGELOG.md
- Cargo.lock
- src/main.rs
- Closed #1666 
- https://github.com/Yamato-Security/hayabusa/actions/runs/15645882479
> fix: append missing newline at EOF in JSONL output

- Cargo.lock
- Cargo.toml
- src/detections/detection.rs
- src/detections/message.rs
- src/detections/rule/base64_match.rs
- src/detections/rule/condition_parser.rs
- src/detections/rule/correlation_parser.rs
- src/main.rs
- src/timeline/computer_metrics.rs
- src/timeline/config_critical_systems.rs
- src/yaml.rs
- src/yaml_expand.rs
I updated it to use hayabusa-evtx 0.9.2 to fix the compile error.
> use evtx 0.9.2 to fix `quick-xml` compile error

- CHANGELOG-Japanese.md
- CHANGELOG.md
- src/detections/detection.rs
- src/options/geoip_search.rs
- Closed #1693 
- https://github.com/Yamato-Security/hayabusa/actions/runs/17794152661
> fix: JSON timeline flag in geo IP lookup
