README-Japanese.md
README-japaneseのルールファイルreadmeへのリンクが間違っていました。
ちゃんと飛べるようにした。
=> fix typo link

src/main.rs
closes #335 
- evtxのファイルパスにおいて隠しファイルを読み込まないようにした #335 
.evtx拡張子となっているものは以下の例だと4つあるが、1つが隠しファイルとなっている。ディレクトリ指定時に隠しファイルを除外し読み込み数が3となっていることと、隠しファイルをファイル指定したときにエラーを返すことを確認済み
```
PS >ls -Recurse .\test_files\evtx\
Directory: ...\hayabusa\test_files\evtx
Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----          2021/11/28     4:36                sub
-a---          2021/12/22    19:35              0 .test1.evtx
-a---          2021/11/28     4:36              0 test.txt
-a---          2021/06/04    11:00              0 test1.evtx
Directory: ...\hayabusa\test_files\evtx\sub
Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a---          2021/11/28     4:36              0 …
```
=> Feature/except hidden file#335

config/exclude-rules-full.txt, config/exclude-rules.txt, config/noisy-rules-full.txt, config/noisy-rules.txt, src/filter.rs
fix #358.
アルゴリズムは、一行ずつ取り出して、#を基準にして、split()で配列に分けて、0番目の添え字に対して、ID validationが通れば、そのIDを対象とすることにしています。
このアルゴリズムがダメだったら、指摘してください。
=> exclude-rules.txtとnoisy-rules.txtをコメントに対応

src/afterfact.rs
closes #381 
- removed csv encode in stdout 
```
>./hayabusa.exe -d .\hayabusa-sample-evtx\ -r ..\hayabusa-rules\
...
2021-10-28 22:41:21.325 +09:00 | FS03.offsec.lan | 1 | high | Process Creation Sysmon Rule Alert | Rule: technique_id=T1059,technique_name=Command-Line Interface  :  Command: "cmd.exe"  :  Path: C:\Windows\System32\cmd.exe  :  User: NT AUTHORITY\SYSTEM  :  Parent Command: C:\Windows\System32\spoolsv.exe
...
2021-11-18 16:42:54.822 +09:00 | PC-01.cybercat.local | 1 | high | Process Creation Sysmon Rule Alert | Rule: technique_id=T1218.004,technique_name=InstallUtil  :  Command: C:\Windows\Microsoft.NET\Framework\v4.0.30319\InstallUtil.exe  /logfile= /LogToConsole=false /U C:\Users\pc1-user\Desktop\zoom-update.exe  :  Path: …
```
=> removed csv quote when output result to stdout #381

src/detections/configs.rs, src/yaml.rs
fix #311
現状、ルール場所を指定するオプションはディレクトリしか指定できない。
ファイルも指定できるようにする。
両方とも同じオプションでできるようにしました。（--rules)
=> ルール場所指定オプションでファイルを扱えるようにする

src/afterfact.rs, src/yaml.rs
Closes #271
yamlのignore部分をチェックする処理はfilterのexculde idで対応することになったため削除。
exclude idの対象になっているルールのチェックの処理を読み込み時の一番最初にもっていく形に変更しました。
これによる処理の出力等に変更はありません
=> remove yaml ignore check#271

src/afterfact.rs, src/detections/detection.rs, src/detections/print.rs
closes #234 
* added MITRE ATT&CK data output in csv output
* MITRE ATT&CK data is described "tags"  in yaml file
``` yaml
tags : 
- attack.execution
- attack.txxxx.yyy 
- test
```
``` csv
Timestamp,Computer,EventID,Level,RuleTitle,Details,MitreAttack,RulePath,FilePath
(timestamp),(Computer),(Event ID),(Level),(RuleTitle),(Details),execution / txxxx.yy / test,(RulePath),(FilePath)
```
``` csv
Timestamp,Computer,EventID,Level,RuleTitle,Details,MitreAttack,RulePath,FilePath
...
2013-10-24 01:21:33.630 +09:00,IE8Win7,4616,medium,Unauthorized System Time Modification,,defense_evasion / t1099 / t1070.006,..\hayabusa-rules\sigma\builtin\security\win_susp_time_modification.yml,.\hayabusa-sample-evtx\DeepBlueCLI\many-events-security.evtx
2013-10-24 01:21:33.630 +09:00,IE8Win7,1,high,Execution Of …
```
=> added mitre attack data output in csv output

Cargo.lock, Cargo.toml, src/main.rs
Fixed #404 
- add crate static_vcruntime to reduce error when target environment  is not installed Visual C++ Redistribute Package
=> Bug/ Fixed error when target environment is not installed vcc redistribute package

src/main.rs
Fixed #422 
- added pull(fetch + merge) process in update option.
``` powershell
PS >git submodule
6d9781e349ef3a9f8210a758b52f0c59d6e7e37b rules (remotes/origin/develop-9-g6d9781e)
PS >.\hayabusa.exe -u -q
Rules updated successfully.
PS >git submodule       
+f8460b5f242f87ef8e34af0a0c26219df61e4577 rules (heads/main)
```
=> Hotfix/not update submodule update#422

Cargo.lock, Cargo.toml
MacとLinuxではOpensslを静的にコンパイルする必要があるようです。
参考：https://blog.davidvassallo.me/2021/06/10/lessons-learned-building-statically-linked-rust-binaries-openssl/
=> Opensslを静的にコンパイルするためにCargo.tomlの設定変更

Cargo.lock, Cargo.toml, src/detections/rule/matchers.rs, src/detections/rule/selectionnodes.rs, src/main.rs
Closed #447 
##What Changed
- Changed downcast library from mopa to downcast-rs (To reduce clippy warn)
- develop branch
``` powershell
> ./hayabusa.exe -d hayabusa-sample-evtx -o developbranch.csv
Analyzing event files: 509
Hayabusa rules: 67
Sigma rules: 1348
Ignored rules: 83
Rule parsing errors: 0
Total enabled detection rules: 1415
Total detections: 12263
Total critical detections: 109
Total high detections: 1574
Total medium detections: 532
Total low detections: 5239
Total informational detections: 4809
Total undefined detections: 0
Unique detections: 349
Unique critical detections: 29
Unique high detections: 155
Unique medium detections: 95
Unique low detections: 44
Unique informational detections: 26
Unique undefined detections: 0
```
- this pull request ver.
```powershell
> …
```
=> changed downcast library from mopa to downcast_rs #447

src/afterfact.rs, src/detections/detection.rs, src/detections/print.rs, src/detections/rule/aggregation_parser.rs, src/detections/rule/count.rs, src/detections/rule/selectionnodes.rs, src/detections/utils.rs, src/main.rs, src/timeline/statistics.rs, src/timeline/timelines.rs, src/yaml.rs
- Fixed Clippy Warnings
- clippy::unnecessary_to_owned
- clippy::single_char_pattern
- clippy::needless_late_init
- clippy::to_string_in_forat_args
- clippy::map_flatten
- clippy::unnecessary_lazy_evaluations
- checked 0 remained clippy warnings
```powershell
>cargo clippy -- -D warnings
Checking hayabusa v1.1.0 (...\hayabusa)
Finished dev [unoptimized + debuginfo] target(s) in 3.06s
>
```
- this pull request result 
```powershell
> ./hayabusa.exe -d hayabusa-sample-evtx -c pr451.csv
Analyzing event files: 509
Sigma rules: 1348
Hayabusa rules: 67
Ignored rules: 83
Rule parsing errors: 0
Total enabled detection rules: 1415
Total detections: 12270
Total critical detections: 109
Total high detections: 1581
Total medium detections: 532
Total low detections: 5239
Total informational …
```
=> Fixed Clippy Warnings

src/detections/print.rs, src/detections/utils.rs
この(プルリク)[https://github.com/Yamato-Security/hayabusa/pull/464]のデグレを修正します。
CSVに出力される値に関して、改行やタブ文字が削除されるのが本来の動作ですが、削除されない感じになっていました。
=> fix degrade for pull req #464

src/yaml.rs
fixed #472
- fixed 
- add  ignore.yml in test_files/yaml/rule/.git folder
``` powershell
PS >ls -Recurse test_files/rules/yaml
Directory: ...\test_files\rules\yaml
Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----          2022/03/30    20:56                .git
-a---          2021/12/25     9:26            408 1.yml
-a---          2021/12/25     9:26            411 error.yml
-a---          2021/12/25     9:26            451 exclude1.yml
-a---          2021/12/25     9:26            688 exclude2.yml
-a---          2021/12/25     9:26            661 exclude3.yml
-a---          2021/12/25     9:26            845 exclude4.yml
-a---          2021/12/25     9:26            837 exclude5.yml
-a---          2021/12/25     9:26 …
```
=> [Bugfix] exculde load yml in git folder#472

src/afterfact.rs
closes #491 
- Changed output level from informational to info
- updated rules submodule
- develop branch 
``` powershell
PS >.\hayabusa.exe -d .\hayabusa-sample-evtx\  -q
...
Analyzing event files: 509
Hayabusa rules: 111
Sigma rules: 2217
Ignored rules: 83
Rule parsing errors: 0
Total enabled detection rules: 2328
Total detections: 14803
Total critical detections: 182
Total high detections: 1881
Total medium detections: 1000
Total low detections: 6303
Total informational detections: 5437
Total undefined detections: 0
Unique detections: 464
Unique critical detections: 32
Unique high detections: 192
Unique medium detections: 131
Unique low detections: 68
Unique informational detections: 41
Unique undefined detections: 0
Elapsed Time: 00:00:29.898
```
- this pull request
``` powershell
PS …
```
=> changed output informational level to info

README-Japanese.md, README.md, config/level_tuning.txt, src/detections/configs.rs, src/filter.rs, src/main.rs, src/options/level_tuning.rs, src/yaml.rs
Closes #511 
簡単な修正なので、こちらでやってみましたが、なぜか最後のルールだけレベルが変わりませんでした。（バグ？）
"SCM Database Privileged Operation" (dae8171c-5ec6-4396-b210-8466585b53e9)がmediumに変わるはずですが、criticalのままです。
使ったlevel_tuning.txtを添付しました。確認をお願いできますか？
[level_tuning.txt](https://github.com/Yamato-Security/hayabusa/files/8517424/level_tuning.txt)
```
grep -r dae8171c-5ec6-4396-b210-8466585b53e9 ./rules/sigma
./rules/sigma/builtin/security/win_scm_database_privileged_operation.yml:id: dae8171c-5ec6-4396-b210-8466585b53e9
```
grepしたら問題なくルールが出てきますし、中身を確認したら特に異常な書き方でもないので、なぜこのルールだけチューニングできないのかな？
=> level_tuning.txtのパスを./rules/configに移動

src/main.rs
Closes #507 
- removed unnecessary hard reset when rules folder not found.
=> Fixed update bug when rules repository not exist and rules folder exist

CHANGELOG-Japanese.md, CHANGELOG.md, README-Japanese.md, README.md, src/afterfact.rs, src/detections/configs.rs, src/detections/detection.rs, src/detections/print.rs
Closes #548 
- added  `-R / --display-record-id` option ( this option is adjusted to both console and csv output).
- console
- csv output
[548.csv](https://github.com/Yamato-Security/hayabusa/files/8786541/548.csv)
- with --full-data
- console
- csv output
[548_full-data.csv](https://github.com/Yamato-Security/hayabusa/files/8786542/548_full-data.csv)
=> display EventRecordID

CHANGELOG-Japanese.md, CHANGELOG.md, README-Japanese.md, README.md, config/channel_abbreviations.txt, src/detections/detection.rs, src/detections/print.rs
Closes #553 
- Display Channel data (no exist in channel_abbrevations.txt) in `Channel` column.
note: To test removed `Microsoft-Windows-Sysmon/Operational,Sysmon` in channel_abbrevations.txt
[553test.csv](https://github.com/Yamato-Security/hayabusa/files/8810010/553test.csv)
=> display default channel name if not defined

Cargo.toml
すみません。やはり、opensslのstatic dependencyは必要のようです。
=> add back openssl dependency

CHANGELOG-Japanese.md, CHANGELOG.md, README-Japanese.md, README.md, src/afterfact.rs, src/detections/print.rs, src/detections/utils.rs, src/main.rs, src/options/level_tuning.rs, test_files/rules/yaml/exclude1.yml, test_files/rules/yaml/exclude2.yml, test_files/rules/yaml/exclude3.yml, test_files/rules/yaml/exclude4.yml, test_files/rules/yaml/exclude5.yml, test_files/rules/yaml/noisy1.yml, test_files/rules/yaml/noisy2.yml, test_files/rules/yaml/noisy3.yml, test_files/rules/yaml/noisy4.yml, test_files/rules/yaml/noisy5.yml
- Added saved file size output which is specified `output` option.
```
PS >./hayabusa.exe -d .\hayabusa-sample-evtx\ -o 595.csv -q
Analyzing event files: 509
Total file size: 131.9 MB
Loading detections rules. Please wait.
Excluded rules: 59
Noisy rules: 5
Rule parsing error rules: 0
Deprecated rules: 0 (0.00%)
Experimental rules: 1574 (61.58%)
Stable rules: 212 (8.29%)
Test rules: 770 (30.13%)
Hayabusa rules: 134
Sigma rules: 2422
Total enabled detection rules: 2556
...
Analysis finished. Please wait while the results are being saved.
Saved file: 595.csv (23.3 MB)
Results Summary:
...
```
=> enhancement output saved file size

Cargo.lock
cargo.tomlでhayabusaを1.4.1にした後に`cargo update`で反映させる必要がありました。
=> cargo lock 1.4.1 update

src/detections/rule/matchers.rs
Closes #633 
633のテストのためにcase insensitiveのstartswith, endwith, containsを追加してみました。
問題なく動作しましたので現状でcase insensitiveでstartswith、endwith,　containsは動作していることを確認しました。
=> added test #633

CHANGELOG-Japanese.md, CHANGELOG.md, src/options/update_rules.rs
Closes #642 
- Removed  starts with `./`  from updated rule path.
```
PS > ./hayabusa.exe -u   -q
[Updated] ADS Created (Modified: 2022/06/21 | Path: rules\hayabusa\sysmon\alerts\Sysmon_15_AlternateDataStreamCreated_SysmonAlert.yml)
...
[Updated] Vulnerable WinRing0 Driver Load (Modified: 2022/07/26 | Path: rules\sigma\sysmon\driver_load\driver_load_vuln_winring0_driver.yml)
Updated Sigma rules: 440
Updated Hayabusa rules: 142
Rules updated successfully.
```
=> Fixed: To remove './' string from update path result. #642

Cargo.lock, Cargo.toml, src/detections/message.rs
- Fix #639.
- Fixed static variable `MESSAGES` Read/Write operartion to be thread safe in insert_message.
- Add race condition reproduction unit test.
- Since [it will fail if not run in a single thread,](https://github.com/Yamato-Security/hayabusa/issues/639#issuecomment-1213229674), add ignore attribute by default.
Run the following command 5 times and confirm that the number of detections is the same.
`hayabusa -d ../hayabusa-sample-evtx -o ...`
Attach the command execution results.
[test-results.zip](https://github.com/Yamato-Security/hayabusa/files/9327948/test-results.zip)
=> Fix race condition in insert_message. #639

src/main.rs
- Fix #664
- Add file existing check when -f option specified.
Execute #664 Step to Reproduce and confirm that Hayabusa not crash and print message as follows.
=> fix: add file existing check when -f option specified. issue #664

src/afterfact.rs
- Fix #662
- Change the source color hashmap LEVEL_ABBR to LEVEL_FULL when output console.
Execute #662 Step to Reproduce and confirm as follows.
- The number of detections (and aggregation) is same as before fix.
- All detection records are colored as follows.
=> fix: Detection result records(crit,med,low level) not colored

Cargo.lock, Cargo.toml
度々すみません。Windows 32ビットバイナリをコンパイルしてみたら、quick-xml 0.24.0+のバージョンでは失敗しています。
rust evtx crateもquick-xmlが0.23.0でないとコンパイルに失敗します。
0.24.0+のバージョンではCDATAのバグを直しているっぽいけど、rust evtx crateではCDATAに対応していないので、今は最新版を使わなくても良さそうです。また、そもそもevtxでCDATAが実際にに使われていないようです。
=> fix quick-xml version

.github/workflows/rust.yml, src/detections/message.rs, src/detections/pivot.rs
Old code consider programer side effect of PIVOT_KEYWORD global var.
So I add auto clear code. Because I wanna to be miss is off.
=> auto clear PIVOT_KEYWORD in every unit test

src/detections/configs.rs
- Fix profile option command usage
- because **verbose-all-field-info**, **verbose-details-and-all-field-info** could not be set.
But above usage is too long ... ? 😅  Is it better to omit ?
=> fix: profile option command usage.

CHANGELOG-Japanese.md, CHANGELOG.md, Cargo.lock, Cargo.toml, src/afterfact.rs, src/detections/configs.rs, src/detections/detection.rs, src/detections/message.rs, src/detections/rule/count.rs, src/detections/rule/matchers.rs, src/detections/rule/mod.rs, src/detections/utils.rs, src/main.rs, src/options/htmlreport.rs
Closes #778 , Closes #780 
- Reduced used memory by using Nested crate
- Skipped rule author, detect counts aggregation when --no-summary option is used
- Replaced unnecessary clone process 
CPU: Ryzen 5700G
RAM: 16GB
OS: WIndows 11
- `hayabusa.exe -f <evtx-file> --set-default-profile standard -o output.csv` memory usage
|step| prev memory usage| memory usage(prev step diff percent)| improved|
|:---| :---| :---| :---|
| start process | 30% | 31%(-) | -|
| finished analyze | 94%(+64%) | 94%(+63%) | 0%|
| finished output | 97%(+3%) | 94%(0%) | 3%|
- `hayabusa.exe -d ../hayabusa-sample-evtx -o output.csv` result
> Elapsed time: 00:00:11.385
> Saved file: 778test.csv (16.3 MB)
- `hayabusa.exe -d ../hayabusa-sample-evtx  -o output.csv --no-summary` result
> Elapsed time: 00:00:09.237
> Saved …
=> Reduce used memory and Skipped rule author, detect counts aggregation when --no-summary option is used

README-Japanese.md, README.md
- Fixed typo 
-  `med` -> `medium`
- remove unnecessary section
=> fix readme typo

CHANGELOG-Japanese.md, CHANGELOG.md, src/afterfact.rs, src/detections/rule/condition_parser.rs, src/detections/rule/count.rs, src/detections/rule/mod.rs, src/main.rs, src/options/update.rs
- Removed `HBFI-` prefix in AllFieldInfo field in json/jsonl output.
- updated changelog
- updated rules
```
>./791.exe -f ..\hayabusa-sample-evtx\DeepBlueCLI\disablestop-eventlog.evtx --set-default-profile all-field-info -o 791.json -j
...
>cat 791.json
{
"Timestamp": "2019-04-28 06:04:25.733 +09:00",
"Computer": "DESKTOP-JR78RLP",
"Channel": "Sys",
"EventID": 104,
"Level": "high",
"RecordID": 9252,
"RuleTitle": "Log File Cleared",
"AllFieldInfo": {
"BackupPath": "",
"Channel": "System",
"SubjectDomainName": "DESKTOP-JR78RLP",
"SubjectUserName": "jwrig"
},
"RuleFile": "Sys_104_High_SysLogCleared.yml",
"EvtxFile": "..\\hayabusa-sample-evtx\\DeepBlueCLI\\disablestop-eventlog.evtx"
}
{
"Timestamp": "2019-04-28 06:04:32.373 +09:00",
"Computer": "DESKTOP-JR78RLP",
"Channel": "Sys",
"EventID": …
```
=> Removed `HBFI-` prefix

CHANGELOG-Japanese.md, CHANGELOG.md, Cargo.lock, Cargo.toml, src/afterfact.rs, src/detections/configs.rs, src/detections/detection.rs, src/detections/message.rs, src/detections/rule/matchers.rs, src/detections/rule/mod.rs, src/detections/rule/selectionnodes.rs, src/detections/utils.rs, src/main.rs, src/options/htmlreport.rs, src/options/level_tuning.rs, src/options/profile.rs, src/yaml.rs
Closes #790 , Closes #789
- To improve memory usage, removed a few call static variables.
- To improve memory usage, replaced Vec<String> with Nested<String>.
- To improve memory usage, replaced String Object in DetectInfo with CompactString.
- Updated changelog.
analyzed result to 2GB evtx file by the following environment.
- CPU: Ryzen 5700G
- RAM: 16GB
- OS: Windows 11
|step| prev memory usage| in 4701a41 memory usage(prev step diff percent)|improved| in fba1688 |
|:---| :---| :---| :---|:--- |
| start process | 31% | 24% | -| 29%|
| finished analyze | 94%(+63%) | 78%(+54%)|  18%| 82%(+53%)|
| finished output | 94%(0%) | 80%(+2%) | 16%  | 83%(+1%)|
output time ( in 4701a41)
```
Elapsed time: 00:03:28.181
Saved file: output.csv (610.9 MB)
```
output time(in fba1688 )
```
Elapsed time: …
```
=> To reduce ram usage and performance, Replaced String with other crate

README-Japanese.md
Fixed typo `キーアライズ` -> `キーエイリアス`
=> fix readme typo key ailas

src/detections/rule/matchers.rs, src/detections/utils.rs
-fixed test data to execute coverage tool(llvm-cov)
got following llvm-cov coverate result
```bash
> cargo install cargo-llvm-cov
> rustup component add llvm-tools-preview
> cargo llvm-cov
```
=> fixed test data to execute coverage tool(llvm-cov)

src/options/update.rs
ルールの間に改行を入れるとルール一覧が長くなるので、戻しました。
これで問題ないと思います。
=> fix update rules spacing

.github/workflows/integration-test.yml
`hayabusa-sample-evtx`に対して、ビルド後の`hayabusa`でコマンド実行をテストするworkflowを作成してみました！
すみません、このworkflowがmainマージ後にしか実行できないため、大変恐縮なのですが、
以下fukusuketリポジトリにて実行した内容で、もし差し支えなければマージいただけると幸いです🙇
- added GitHub Actions for Hayabusa integration test.
- clone hayabusa-sample-evtx
- run hayabusa commands
- check that the return code of all commands is 0
1. Go to [GitHub Actions](https://github.com/Yamato-Security/hayabusa/actions).
2. click `Integration Test` in left menu.
4. click `Run worflow`.
5. choose branch you want to run test, then click `Run workflow`
When I run the workflow manually.
Run the tests on the following three OS in parallel.
- ubuntu-20.04
- windows-2019
- macos-12
Run the following 13 commands, and if the return code is not 0, the workflow will fail.
- `help`
- `update-rules -q`
- …
=> add GitHub Actions for integration test

README-Japanese.md, README.md
- fixed pivot-keywords-list short option (wrong: `-P` -> correct: `-p`) in readme.
=> fixed pivot-keywords-list short option

CHANGELOG-Japanese.md, CHANGELOG.md, Cargo.toml
codegen-units=1を追加すると、コンパイルの並行処理が無くなるので、コンパイルがより最適化されるはずですが、-100kbのファイルサイズ以外はあまり変わらなくて、コンパイル時間が長くなっているので、CI/CDテスト等が遅くならないようにデフォルトの設定に戻したいです。リリース時だけローカル環境でcodegen-units=1の設定してバイナリをコンパイルします。
=> remove codegen-units 1

src/main.rs
- Fixed bug when no command and global options 
<details>
<summary>--no-color option only</summary>
```pwsh
PS >./845.exe --no-color
╔╗ ╔╦═══╦╗  ╔╦═══╦══╗╔╗ ╔╦═══╦═══╗
║║ ║║╔═╗║╚╗╔╝║╔═╗║╔╗║║║ ║║╔═╗║╔═╗║
║╚═╝║║ ║╠╗╚╝╔╣║ ║║╚╝╚╣║ ║║╚══╣║ ║║
║╔═╗║╚═╝║╚╗╔╝║╚═╝║╔═╗║║ ║╠══╗║╚═╝║
║║ ║║╔═╗║ ║║ ║╔═╗║╚═╝║╚═╝║╚═╝║╔═╗║
╚╝ ╚╩╝ ╚╝ ╚╝ ╚╝ ╚╩═══╩═══╩═══╩╝ ╚╝
by Yamato Security
Hayabusa 2.0.0
Yamato Security (https://github.com/Yamato-Security/hayabusa) @SecurityYamato)
Usage:
hayabusa.exe <COMMAND> [OPTIONS]
hayabusa.exe help <COMMAND>
Commands:
csv-timeline         Save the timeline in CSV format
json-timeline        Save the timeline in JSON/JSONL format
logon-summary        Print a summary of successful and failed logons
metrics              Print event ID metrics
pivot-keywords-list  Create a list of …
```
=> fix: bug when no command and global options

src/afterfact.rs
- Fixed unwrap error when geoip field was not found in ext_field
- main branch -> ref: https://github.com/Yamato-Security/hayabusa/issues/905#issue-1570931245
- this pull request
```
> ./test.exe json-timeline -d ../hayabusa-sample-evtx -o test.json
...
Analyzing event files: 582
Total file size: 148.5 MB
Loading detections rules. Please wait.
Excluded rules: 15
Noisy rules: 7 (Disabled)
Experimental rules: 1690 (49.69%)
Stable rules: 220 (6.47%)
Test rules: 1491 (43.84%)
Hayabusa rules: 148
Sigma rules: 3253
Total enabled detection rules: 3401
Scanning in progress. Please wait.
582 / 582 [=========================================================================================================================================================================================================== …
```
=> Fixed unwrap error when geoip field was not found in ext_field

CHANGELOG-Japanese.md, CHANGELOG.md, src/afterfact.rs
- Fixed misalignment of CmdLine and Payload fields in json output. 
- OS: Windows 11
- Hard: Memory 16GB , Core 8, SSD
> ./hayabusa.exe json-timeline -t "../hayabusa-sample-evtx/EVTX-to-MITRE-Attack/TA0007-Discovery/T1087-Account discovery/ID4103-4104 - SPN discovery (moder nPowerShell).evtx" -o out.json
<details>
<summary>[before]((https://github.com/Yamato-Security/hayabusa/commit/6e2276ac1ddc91ce74ec7f607c6e0b62ee7ce10b) )</summary>
```
{
"Timestamp": "2021-01-30 18:13:13.309 +09:00",
"Computer": "fs02.offsec.lan",
"Channel": "PwSh",
"EventID": 4103,
"Level": "info",
"RecordID": 16015,
"RuleTitle": "PwSh Pipeline Exec",
"Details": {
"Payload": "",
"CommandInvocation(Out-Default)": "\"Out-Default\""
}
}
...
```
</details>
<details>
<summary>[This …
=> Fixed misaligned fields in json output

CHANGELOG-Japanese.md, CHANGELOG.md, Cargo.lock, Cargo.toml, src/afterfact.rs, src/detections/configs.rs, src/detections/detection.rs, src/detections/message.rs, src/main.rs, src/timeline/metrics.rs, src/timeline/timelines.rs
- Added channel names shorter in the metrics/csv-timeline/json-timeline command.
<details>
<summary>main branch result</summary>
```
Analyzing event files: 584
Total file size: 137.1 MB
584 / 584 [==========================================================================] 100.00 %
Total Event Records: 47471
╭───────┬─────────┬────────────────────────────────────────────────────────────┬───────┬────────────────────────────────────────────────────────────────────────────────────────╮
│ Count ┆ Percent ┆ Channel                                                    ┆ ID    ┆ Event                                                                                  │
╞═══════╪═════════╪════════════════════════════════════════════════════════════╪═══════╪═══════════════════════════════════════════════ …
```
=> Added channel names shorter in the metrics/csv-timeline/json-timeline command

Cargo.lock, Cargo.toml, src/detections/configs.rs, src/main.rs
If there are no other PRs you two want to add before 2/22 in the 2.2.2 release, then I think it is good as it is now.
Comparison with 2.2.0:
Total & Unique detections: same
Speed: 25:42 -> 26:09 (About 1.7% slower) I think this is because the new evtx crate is slower to avoid parse errors and we shorten channel names generically as well. But I think these two things are worth the slight speed decrease.
Memory: 6.5GB -> 6.4GB (Seems to use slightly less memory)
File size: 1,239,657 KB -> 1,239,654 KB (Only 3KB smaller with smaller channel names...)
=> finalize 2.2.2

CHANGELOG-Japanese.md, CHANGELOG.md, Cargo.lock, Cargo.toml, src/detections/configs.rs, src/detections/utils.rs, src/timeline/timelines.rs
- replaced file check of `rules/event_id_info.txt` with `rules/channel_eid_info.txt`
- added new version changelog template and fixed typo in changelog
I checked to execute with the following command and `-d hayabusa-sample-evtx -o test`. All were confirmed to be OK, with no error logs or other output.
- csv-timeline
- json-timeline
- metrics
- logon-summary
- pivot-keywords-list
=> Removed ref old eid info file

README-Japanese.md, README.md, src/afterfact.rs, src/detections/pivot.rs, src/detections/utils.rs
- Fix set-default-profile's option document was incorrect.
- `-P` -> `-p`
- Use long style option in README
`-p` -> `--profile`
- I changed the command samples in the README to use long options because short option was unclear what omitting the options meant.
- `set-default-profile` is command
- https://github.com/Yamato-Security/hayabusa/blob/04f82194530d9d6b6bfceaff3a2311e776bb7402/README-Japanese.md?plain=1#L384-L392
- `set-deafult-profile` 's option is `-p`
- https://github.com/Yamato-Security/hayabusa/blob/89c24f654945e375d2e3f725e7eb6fcb97bd8ba5/src/detections/configs.rs#L632-L640
- https://github.com/Yamato-Security/hayabusa/blob/89c24f654945e375d2e3f725e7eb6fcb97bd8ba …
=> Fix: set-default-profile's README option was incorrect

CHANGELOG-Japanese.md, CHANGELOG.md, Cargo.lock, Cargo.toml, src/detections/rule/condition_parser.rs
- Fixed #956
- Added rule `conditions:` block conversion process internally with the following specifications before rule compilation/tokenize
-  `1 of selection*` -> `(select1 or select2 or select3)`
-  `all of selection*` -> `(select1 and select2 and select3)`
- OS: macOS montery version 13.1
- Hard: Macbook Air(M1, 2020) , Memory 8GB, Core 8
Detection count
of rule which has `1 of selection_*` is the same before/after.
- main: `./hayabusa-2.2.2 -d ... -r` [hayabusa-rules/win_security_pass_the_hash_2.yml](https://github.com/Yamato-Security/hayabusa-rules/blob/main/sigma/builtin/security/win_security_pass_the_hash_2.yml)
- [This PR](https://github.com/Yamato-Security/hayabusa/compare/support-condition-allof-1of): `./hayabusa-new -d ... -r` …
=> feat: Support `1 of selection*` and `all of selection*`

CHANGELOG-Japanese.md, CHANGELOG.md, src/detections/configs.rs
The `--enable-deprecated-rules` and `--enable-unsupport-rules` are useful options that I want to use frequently but are long to type so I added short options. Please check if this is ok.
=> add short options

CHANGELOG-Japanese.md, CHANGELOG.md, src/detections/configs.rs
- Changed help string and option sorted
<details>
<summary>main</summary>
```
>./main.exe help csv-timeline
...
Filtering:
-E, --EID-filter                Scan only common EIDs for faster speed (./rules/config/target_event_IDs.txt)
-D, --enable-deprecated-rules   Enable rules marked as deprecated
-n, --enable-noisy-rules        Enable rules marked as noisy (./rules/config/noisy_rules.txt)
--exclude-status <STATUS>   Ignore rules according to status (ex: experimental) (ex: stable,test)
-u, --enable-unsupported-rules  Enable rules marked as unsupported
-e, --exact-level <LEVEL>       Scan for only specific levels (informational, low, medium, high, critical)
-m, --min-level <LEVEL>         Minimum level for rules (default: informational)
--timeline-end <DATE>       End time of the event logs …
```
=> sorted filtering options

CHANGELOG-Japanese.md, CHANGELOG.md, src/afterfact.rs
- Trim extra space in levels when outputting to files(csv, json, jsonl)
- csv-timeline
`./979.exe csv-timeline -d ../hayabusa-sample-evtx -o 969-hse.csv -p super-verbose --debug -q`
[979CSVcomp.zip](https://github.com/Yamato-Security/hayabusa/files/11062988/979CSVcomp.zip)
- json-timeline
`./979.exe json-timeline -d ../hayabusa-sample-evtx -o 969-hse.json -p super-verbose --debug -q`
```
> cat ./979.json | jq .Level | sort | unique
"crit"
"high"
"info"
"low"
"med"
```
- jsonl
`./979.exe json-timeline -d ../hayabusa-sample-evtx -o 969-hse.json -p super-verbose --debug -q -L`
[979JSONLcomp.zip](https://github.com/Yamato-Security/hayabusa/files/11062981/979JSONLcomp.zip)
=> Trim extra space in levels when outputting to files

src/filter.rs, src/yaml.rs
This reverts commit 096698ad31b3df77ceb4f59f3164229a6bae0d49.
=> Revert "perf(filter, yaml): replaced String with ComapctString"

Cargo.toml
Cargo.tomlにレポジトリのリンクを追加しました。
GithubページでUsed by...の一覧が表示されるように必要かもしれないので、追加してみました。
=> added repo link

src/detections/configs.rs
@itiB 
PRありがとうございます！引数の組み合わせ対応良いですね。
`-i`を`--keywords`をrequireするより、エラーを出した方が分かりやすそうなので、少し変えてみました。
ご確認ください。
```
./target/release/hayabusa search -d ../hayabusa-sample-evtx -r ".*" -i
error: the argument '--regex <REGEX>' cannot be used with '--ignore-case'
```
```
./target/release/hayabusa search -d ../hayabusa-sample-evtx -r ".*" -k "hi"
error: the argument '--regex <regex>' cannot be used with '--keywords <keywords>'
```
因みに、long option nameが大文字にした理由はありますか？
実際の小文字のオプション名に変えましたが、大文字の方が良いのであれば、戻しましょう。
=> add conflicting args

CHANGELOG-Japanese.md, CHANGELOG.md, src/detections/utils.rs, src/timeline/search.rs
- added output Event.UserData to AllFieldInfo in csv-timeline, json-timeline, search command
- main
```
>./main.exe csv-timeline -d ..\hayabusa-sample-evtx\ -r .\1006test.yml -o 1006main.csv -p super-verbose -q
...
> cat 1006main.csv
"Timestamp","Computer","Channel","Provider","EventID","Level","MitreTactics","MitreTags","OtherTags","RecordID","RuleTitle","RuleAuthor","RuleCreationDate","RuleModifiedDate","Status","Details","RuleFile","EvtxFile","AllFieldInfo"
"2019-08-28 12:36:49.826 +09:00","MSEDGEWIN10","RDP-CoreTS","MS-Win-RemoteDesktopServices-RdpCoreTS",70,"crit","Exec ¦ PrivEsc ¦ Evas ¦ CredAccess ¦ LatMov ¦ Impact","T1203 ¦ T1068 ¦ T1211 ¦ T1212 ¦ T1210 ¦ T1499.004","",979,"Test Event","Test","2020/01/15","2022/10/22","experimental","DisplayDriverName: …
```
=> added output Event.UserData to AllFieldInfo

.github/workflows/rust.yml
fix #815
- Changed 1
I update version of Swatinem/rust-cache and ClementTsang/cargo-actio.
See Next Comment.
=> update github-action version to erase deprecated error

Cargo.lock, Cargo.toml, README-Japanese.md, README.md, config/pivot_keywords.txt, src/main.rs, src/options/pivot.rs
=> enhance pivot terminal output

CHANGELOG-Japanese.md, CHANGELOG.md, src/main.rs, src/options/pivot.rs
- Changed 1
Enabling --no-color on pivot, headers is normal color.
I want to confirm under.
A message that's "No keywords found" is always RED.
Is it OK?
=> enable --no-color with pivot of headers

src/afterfact.rs
ルール作者のテーブルの幅が最近思ったより広くなっちゃって、ターミナルを全画面にしないとテーブルが崩れてしまうケースが多いので、40文字を27文字に減らしました。
changelog更新や新しいリリースほどではないので、2.5.1に入れて、新しいバイナリを再アップロードしようと思ってますが、どうでしょうか？
=> shorten author name length

CHANGELOG-Japanese.md, CHANGELOG.md, src/afterfact.rs, src/detections/message.rs, src/main.rs
- fixed no output of MitreTactics, MitreTags, OtherTags in json-timeline 
- added test to json output #864 
I would appreciate it if you could review when you have time
=> fixed MitreTactics, MitreTags, OtherTags do not output in json timeline output

CHANGELOG-Japanese.md, CHANGELOG.md, src/afterfact.rs, src/detections/configs.rs
- Fixed no detection frequency timeline output when `no-summary` option is used.
=> Fixed no detection frequency timeline output when no-summary option is used.

CHANGELOG-Japanese.md, CHANGELOG.md, Cargo.lock, src/detections/configs.rs
- Changed 1
In disp_abbr_generic, modified to search case-insensitive chanell strings for search targets.
- Before modification
- After modification
=> make channel name case-insensitive #1066

CHANGELOG-Japanese.md, CHANGELOG.md, src/afterfact.rs, src/detections/configs.rs
- fixed unescaped control character c causing jq parsing errors
=> fixed unescaped control character c causing jq parsing errors

CHANGELOG-Japanese.md, CHANGELOG.md, src/main.rs, src/timeline/metrics.rs, src/timeline/timelines.rs
- fixed `metrics` and `logon-summary` records and `csv-timline` show different total event records.
- modified not to output standard output when the output option is set in metrics.  (1c9d00a1a5099ee578efefb22e668ee502b741d6)
=> fixed `metrics` and `logon-summary` records and `csv-timline` show different total event records

src/afterfact.rs
- fixed result summary table breaks
=> fixed result summary table breaks

CHANGELOG-Japanese.md, CHANGELOG.md, src/detections/configs.rs
- Fixed `--timeline-start` and `--timeline-end` do not work correctly with `json-timeline` command. 
=> Fixed `--timeline-start` and `--timeline-end` do not work correctly with `json-timeline` command.

CHANGELOG-Japanese.md, CHANGELOG.md, src/detections/configs.rs
- Fixed `--timeline-start` and `--timeline-end` do not work correctly with `pivot-keywords-list` command.
=> 1150 timeline start and timeline end do not work with pivot keywords list

.github/workflows/integration-test.yml
Update GitHub Actions for integration test.
- added test case
- added `search` command test
- rename `metrics` to `eid-metrics/computer-metrics` command
I made a copy with fukusuket count and confirmed the job success as follows.
https://github.com/fukusuket/hayabusa-ci/actions/runs/5775070895/job/15652670782
I would appreciate it if you could review when you have time🙏
=> fix: Update GitHub Actions for Integration test

src/afterfact.rs, src/detections/message.rs, src/detections/utils.rs
- outputted  newline and tab char  in `AllFieldInfo` and `ExtraFieldInfo`  field newline and tab char 
=> fixed removed `AllFieldInfo` and `ExtraFieldInfo`  field newline and tab char 

CHANGELOG-Japanese.md, CHANGELOG.md, src/main.rs
- Fixed #1209 
- Explicitly set * to `stored_static.include_status`
- If `include_status` is not set, when creating a list of yml rules with the read_dir function, it will be determined that there are no target rules
- OS: macOS Sonoma version 14.0
The updated rule name will be displayed as shown below.
```
fukusuke@fukusukenoAir hayabusa-2.10.0-all-platforms % ./hayabusa update-rules
╔╗ ╔╦═══╦╗  ╔╦═══╦══╗╔╗ ╔╦═══╦═══╗
║║ ║║╔═╗║╚╗╔╝║╔═╗║╔╗║║║ ║║╔═╗║╔═╗║
║╚═╝║║ ║╠╗╚╝╔╣║ ║║╚╝╚╣║ ║║╚══╣║ ║║
║╔═╗║╚═╝║╚╗╔╝║╚═╝║╔═╗║║ ║╠══╗║╚═╝║
║║ ║║╔═╗║ ║║ ║╔═╗║╚═╝║╚═╝║╚═╝║╔═╗║
╚╝ ╚╩╝ ╚╝ ╚╝ ╚╝ ╚╩═══╩═══╩═══╩╝ ╚╝
by Yamato Security
Start time: 2023/11/04 23:15
- Uncommon PowerShell Hosts (Modified: 2023/11/03 | Path: rules/sigma/builtin/powershell/powershell_classic/posh_pc_alternate_powershell_hosts.yml)
- …
```
=> fix: set include_status * when `update-rules` command.

src/detections/message.rs
- Fixed #1215 
- OS: macOS Sonoma version 14.0
I confirmed that the problem does not occur using the steps to reproduce #1215 
```
% ./hayabusa csv-timeline -f ../apt29_evals_day1_manual_2020-05-01225525.json -J -r test.yml -w -q -o out.csv -C
Start time: 2023/11/12 22:20
Total event log files: 1
Total file size: 385.3 MB
Loading detection rules. Please wait.
Test rules: 1 (100.00%)
Hayabusa rules: 1
Total enabled detection rules: 1
Output profile: standard
Scanning in progress. Please wait.
[00:00:03] 1 / 1   [========================================] 100%
Scanning finished. Please wait while the results are being saved.
Rule Authors:
╭──────────╮
│ TEST (1) │
╰──────────╯
Results Summary:
Events with hits / Total events: 2,842 / 196,081 (Data reduction: 193,239 events (98.55%))
Total | …
```
=> fix: added initial value when there is no `Data` field

Cargo.lock, Cargo.toml, src/detections/configs.rs
closes #1232 
I made the required options a little stricter and updated `csv` to 1.3 as it is just a minor update.
Please check when you have time.
=> added stricter checks for options

CHANGELOG-Japanese.md, CHANGELOG.md, src/main.rs
- Added message about reporting issues and FPs when `csv-timeline` or `json-timeline` command was used.
=> Added message about reporting issues and FPs

CHANGELOG-Japanese.md, CHANGELOG.md, src/detections/configs.rs
- Fixed a bug in the `csv-timeline`, `json-timeline`, `eid-metrics`, `logon-summary`, `pivot-keywords-list` and `search` commands so that processing is not executed when the option (`-l`, `-f` or `-d`) specifying the file to be investigated does not exist.
=> added require `-d`, `-l` or `-f` with commands

CHANGELOG-Japanese.md, CHANGELOG.md, Cargo.lock, Cargo.toml, contributors.txt, src/detections/configs.rs
I have finalized 2.12.0. Please check when you have time.
=> finalize 2.12.0

CHANGELOG-Japanese.md, CHANGELOG.md, src/afterfact.rs
- Modified to Output JSON format in `json-timeline` command for standard output.
=> output json format in json timeline for standard output

src/detections/rule/condition_parser.rs
- I've changed the modifier of the argument in the function 'replace_subtoken()' from &self to self. This helps us to reduce clone() uses.
This is just a first step to reduce clone uses so we cannot close the issue 787.
Some testcases have failed on this branch but testcases also failed on main branch as I mentioned in slack(https://yamatosecurity2.slack.com/archives/C01BBBC4DU7/p1706798362376809).
Please check this.
=> change self modifier to reduce clone()

README.md, src/detections/configs.rs
- added required option filter in search command
- added conflict command filter in multiple row and json/jsonl output 
- Please check previous version result in #1257  description.
- this PR
-  checked in search command without keywords/regex option.
```pwsh
❯ ./1257.exe search -d ../hayabusa-sample-evtx
error: the following required arguments were not provided:
<--keyword <KEYWORD...>|--regex <REGEX>>
Usage: 1257.exe search <--directory <DIR>|--file <FILE>|--live-analysis> <--keyword <KEYWORD...>|--regex <REGEX>>
```
- checked conflict multiline option to JSON-output and JSONL-output.
```pwsh
> ./1257.exe search -d ../hayabusa-sample-evtx -M -o test.jsonl -J
error: the argument '--multiline' cannot be used with '--JSON-output'
Usage: 1257.exe search --multiline --output <FILE> …
```
=> fixed `search` command line options associate

src/detections/rule/condition_parser.rs
#787 
change parse condition logic in order to remove unnecessary function and in order not to create unnecessary token instance.
The testcases have passed.
=> Remove replace subtoken

CHANGELOG-Japanese.md, CHANGELOG.md, Cargo.lock, Cargo.toml
I removed unused crates I found from `cargo machete`
```
cargo machete --with-metadata
Analyzing dependencies of crates in this directory...
cargo-machete found the following unused dependencies in Cargo.toml:
crossbeam_utils
flate2
lock_api
mockall
num_cpus
openssl
quick_xml
```
Also sorted alphabetically to make easier to check.
=> remove unused crates

Cargo.lock, Cargo.toml, src/afterfact.rs, src/detections/configs.rs, src/detections/detection.rs, src/detections/message.rs, src/main.rs, src/timeline/computer_metrics.rs
This is just a refactoring for low memory option and I'm going to add low memory option in a next pull request.
I've refactored the current code for creating low memory option as follows
- remove MESSAGES and MESSAGEKEYS from message.rs not to store log record in static field
- refactor afterfact.rs
- delete testcases that check the behavior of message::MESSAGES
=> refactoring for low memory option

CHANGELOG-Japanese.md, CHANGELOG.md, src/detections/rule/aggregation_parser.rs
- Closed #1278
- OS: macOS Sonoma version 14.2.1
- Hayabusa v2.14.0-dev
- rustc 1.76.0
I confirmed that there are no differences in the resulting CSV as shown below before after fix.
```
% ./hayabusa-new csv-timeline -d ../hayabusa-sample-evtx -o new.csv -w --debug -C -q
% ./hayabusa-main csv-timeline -d ../hayabusa-sample-evtx -o main.csv -w --debug -C -q
% diff main.csv new.csv
%
```
I also confirmed that there were no rule parsing errors and that the number of rules(4077) loaded was the same.
```
% ./hayabusa-main csv-timeline -d ../hayabusa-sample-evtx -o main.csv -w --debug -C -q
Start time: 2024/02/27 23:41
Total event log files: 583
Total file size: 137.1 MB
Loading detection rules. Please wait.
Excluded rules: 26
Noisy rules: 12 (Disabled)
Deprecated rules: 202 (4.95%) (Disabled) …
```
=> perf: use slice instead of `replacen` in AggegationConditionCompiler.tokenize()

CHANGELOG-Japanese.md, CHANGELOG.md, src/main.rs, src/timeline/search.rs, src/timeline/timelines.rs
- Reordered `search` result fields to look similar to the `csv-timeline` command results.
=> reorder `search` result fields

CHANGELOG-Japanese.md, CHANGELOG.md, Cargo.lock, Cargo.toml, src/detections/configs.rs
@hitenkoku @fukusuket I decided to release 2.15.0 with the `windash` support to give people time to upgrade before we stop doing the `windash` conversion on the backend.
=> finalize 2.15.0

CHANGELOG-Japanese.md, CHANGELOG.md, src/detections/detection.rs, src/detections/rule/aggregation_parser.rs, src/detections/rule/count.rs
- Closed #1339
I run  with the following rules,
`./hayabusa csv-timeline -d ../hayabusa-sample-evtx -w -A -a  -D -n -u -q -r test.yml`
```Yaml
title: TEST_TITLE
details: ''  #Cannot be used because this is a count rule
description: TEST
id: 5e00cf44-84bb-4083-8ae6-213005b2307a
level: informational
status: test
detection:
selection:
Channel: Security
EventID: 4625
filter:
IpAddress: "-"
condition: selection and not filter | count() by IpAddress,SubStatus,LogonType >= 2
timeframe: 5d
```
then I confirmed multiple key grouping works as follows.
```
Timestamp · RuleTitle · Level · Computer · Channel · EventID · RecordID · Details · ExtraFieldInfo
2016-09-20 01:50:06.513 +09:00 · TEST_TITLE · info · - · - · - ·  · Count: 3558 ¦ IpAddress: 192.168.198.149 ¦ SubStatus: 0xc000006a ¦ LogonType: 3 …
```
=> feat: add support for multiple key grouping in count condition

CHANGELOG-Japanese.md, CHANGELOG.md, Cargo.toml
Closes https://github.com/Yamato-Security/hayabusa/issues/1348
=> enable overflow checks

CHANGELOG-Japanese.md, CHANGELOG.md, src/detections/field_data_map.rs, src/detections/message.rs, src/detections/utils.rs
- Closed #1350 
- added support `Provider_Name` in data mapping config(Optional)
- added support multiple `Provider_Name`  in data mapping config(Optional)
- added support `Data[x]` notation in data mapping config. 
=> feat: add support for `Data[x]` notation and `Provider_Name`(field mapping feature's config)

CHANGELOG-Japanese.md, CHANGELOG.md, src/detections/detection.rs, src/detections/rule/correlation_parser.rs, src/detections/rule/mod.rs, src/main.rs
- Closed #1337 
The following points are not supported because they require more time to implement. 
I will consider addressing them as separate PR depending on priority.
- https://github.com/Yamato-Security/hayabusa/issues/1342
- [Multiple yaml in one file](https://github.com/SigmaHQ/sigma-specification/blob/version_2/Sigma_meta_rules.md#failed-logins-followed-by-successful-login)
- Multiple `Condition`(e.g.  100 > count > 1)
- Recursive Correlation rule
=> feat: add support for Sigma Correlation Event count

CHANGELOG-Japanese.md, CHANGELOG.md, src/detections/rule/correlation_parser.rs
- added support for correlation rule's `name` lookup
- ref: https://blog.sigmahq.io/introducing-sigma-correlations-52fe377f2527
=> feat: add support for correlation `name` lookup

.github/workflows/timeline-diff.yml
Added GitHub Actions for csv/json timeline diff check. This Action does the following for both main/selected branch.
- `checkout <main/selected branch>`
- `cargo run --release -- update-rules -q`
- `cargo run --release -- csv-timeline -d ./hayabusa-sample-evtx -o dev(main).csv -p super-verbose -q -w -D -n -u`
- `cargo run --release -- json-timeline -d ./hayabusa-sample-evtx -o dev(main).jsonl -L -p super-verbose -q -w -D -n -u`
after that execute following diff command.
- `diff dev.csv main.csv`
- `diff dev.jsonl main.jsonl`
If there is a difference in the diff results, the Actions will fail.
The execution trigger for this action is manual, so it does not affect usual workflow, etc.
Choose the branch you want to compare with the main branch in the following screen and perform the Action …
=> test: add GitHub Actions for (json/csv)timeline diff check

Cargo.lock, Cargo.toml
I updated the crates to use the latest hayabusa-evtx which fixes errors with the latest quick-xml
=> bump crates

CHANGELOG-Japanese.md, CHANGELOG.md, Cargo.lock, src/afterfact.rs, src/detections/detection.rs, src/detections/message.rs, src/detections/rule/count.rs, src/detections/rule/mod.rs
- Closed #1373
- Closed #1375
- Related #1342
No difference in the result file compared to the main branch.
https://github.com/Yamato-Security/hayabusa/actions/runs/9844009215
All commands work properly.
https://github.com/Yamato-Security/hayabusa/actions/runs/9844007839
=> fix: count up `Event with hits` when aggregation/correlation rule

CHANGELOG-Japanese.md, CHANGELOG.md, src/detections/rule/matchers.rs
- added en-dash and other permutations for windash modifier
=> feat(matchers): added en-dash and other permutations for windash modifier

CHANGELOG-Japanese.md, CHANGELOG.md, config/mitre_tactics.txt
The following pull request changed the tag format of Sigma's `MitreTactics` from `_` to `-`. So I modified the Hayabusa side to follow that specification.
- https://github.com/SigmaHQ/sigma/pull/4950
- Example:
- https://github.com/SigmaHQ/sigma/pull/4950/files#diff-cf3209c2a0484833254ef8c8f77791dc32bd46a005e94971468e41e886e2f456
The above pull request is for today, so it will be merged in today's job in the hayabusa_rules repository.
I have confirmed that we can output `MitreTactics` for the latest Sigma(https://github.com/SigmaHQ/sigma/commit/760597da11cd5cfde39b64de06efa8175e98ce7a) repository as follows.
```json
{
"Timestamp": "2021-11-18 16:43:22.487 +09:00",
"RuleTitle": "EVTX Created In Uncommon Location",
"Level": "med",
"Computer": "PC-01.cybercat.local",
"Channel": "Sysmon", …
```
=> chg: Sigma v2 compliant `MitreTactics` tag format

CHANGELOG-Japanese.md, CHANGELOG.md, src/afterfact.rs, src/detections/message.rs, src/detections/utils.rs, src/main.rs, src/options/profile.rs, src/yaml.rs
- embedded config files in binary
=> feat: embedded config files to binary #1370

CHANGELOG-Japanese.md, CHANGELOG.md, src/detections/rule/matchers.rs
- Closed #1396 
No difference in the result file compared to the main branch.
https://github.com/Yamato-Security/hayabusa/actions/runs/10411818917
All commands work properly.
https://github.com/Yamato-Security/hayabusa/actions/runs/10411817930
=> feat: add support for Sigma v2 `|re` sub modifiers

CHANGELOG-Japanese.md, CHANGELOG.md, src/detections/rule/matchers.rs
- added sigma v2 cased modifier support
=> added sigma v2 cased modifier support

CHANGELOG-Japanese.md, CHANGELOG.md, Cargo.lock, Cargo.toml, src/detections/configs.rs
I finalized 2.17.0. Please check when you have some time.
=> finalize 2.17.0

.github/workflows/supported_modifier.yml
The path to Actions in supported-modifier was incorrect and has been corrected.
=> Fix: Github Actions hayabusa-rule path

CHANGELOG-Japanese.md, CHANGELOG.md, Cargo.lock, Cargo.toml, src/detections/configs.rs, src/detections/rule/matchers.rs, src/main.rs
=> feat(matchers): added fieldref modifier

.github/workflows/release.yml
- Closed #1239 
- **Use workflow from** : normally, specify main.
- **release_ver**: target version name (use as zip package and exe name)
- **branch_or_tag** :  target git branch or tag name
Tested in the fukusuket repository.
https://github.com/fukusuket/hayabusa/actions/runs/11191344760
=> feat: add GitHub Actions for auto build packages

.github/workflows/integration-test.yml, .github/workflows/timeline-diff.yml
Added integration-test and csv/json timeline diff test for encoded_rules and single config.
I confirmed the operation in the fukusuket repository.
- https://github.com/fukusuket/hayabusa/actions/runs/11215400042
- https://github.com/fukusuket/hayabusa/actions/runs/11215246648/job/31172037737
=> test: add integration-test/csv(json)-timeline diff-test for encoded_rules/single config

.github/workflows/release.yml
- Closed #1429 
I will check if `update-rules` can be executed when there is a new commit in `hayabusa_rules`.
- https://github.com/Yamato-Security/hayabusa/actions/runs/11254983192
```
fukusuke@fukusukenoMacBook-Air hayabusa-2.18.0-mac-arm % ./hayabusa-2.18.0-mac-aarch64 update-rules -q
Start time: 2024/10/10 07:31
- Renamed Powershell Under Powershell Channel (Modified: 2024-10-08 | Path: rules/sigma/builtin/powershell/powershell_classic/posh_pc_renamed_powershell.yml)
- CodeIntegrity - Unmet Signing Level Requirements By File Under Validation (Modified: 2024-10-08 | Path: rules/sigma/builtin/code_integrity/win_codeintegrity_attempted_dll_load.yml)
- Antivirus Password Dumper Detection (Modified: 2024-10-08 | Path: rules/sigma/builtin/category/antivirus/av_password_dumper.yml)
- …
```
=> fix: copy all .git commit history by specifying fetch-depth 

.github/workflows/release.yml
- Closed #1431 
- https://github.com/Yamato-Security/hayabusa/actions/runs/11284966384
Arm x MUSL compiling will result in an error, so exclude it from the scope.
- https://github.com/fukusuket/hayabusa/actions/runs/11284911304/job/31386857482
=> fix: specify compile target explicitly in Release Automation

CHANGELOG-Japanese.md, CHANGELOG.md, src/detections/rule/correlation_parser.rs
- Closed #1442 
All commands completed successfully.
https://github.com/Yamato-Security/hayabusa/actions/runs/11313889055
No difference(csv/json) from main branch's results as follows.
https://github.com/Yamato-Security/hayabusa/actions/runs/11313890870
=> fix: make `group-by` optional for correlation

.github/workflows/release.yml
Change to the following Artifact name
- Linux ARM 64-bit GNU (`hayabusa-x.x.x-lin-aarch64-gnu`)
- Linux Intel 64-bit GNU (`hayabusa-x.x.x-lin-x64-gnu`)
- Linux Intel 64-bit MUSL (`hayabusa-x.x.x-lin-x64-musl`)
- macOS ARM 64-bit (`hayabusa-x.x.x-mac-aarch64`)
- macOS Intel 64-bit (`hayabusa-x.x.x-mac-x64`)
- Windows ARM 64-bit (`hayabusa-x.x.x-win-aarch64.exe`)
- Windows Intel 64-bit (`hayabusa-x.x.x-win-x64.exe`)
- Windows Intel 32-bit (`hayabusa-x.x.x-win-x86.exe`)
- https://github.com/Yamato-Security/hayabusa/actions/runs/11471678588
=> fix:  Changed Release automation Action's Artifact name 

.github/workflows/timeline-diff.yml, CHANGELOG-Japanese.md, CHANGELOG.md, src/timeline/metrics.rs, src/timeline/timelines.rs
- Closed #1468 
- Closed #1477 
All commands completed successfully.
https://github.com/Yamato-Security/hayabusa/actions/runs/11724197180
=> feat: add RDS log to `logon-summary`

CHANGELOG-Japanese.md, CHANGELOG.md, Cargo.lock, Cargo.toml, src/main.rs
Closes https://github.com/Yamato-Security/hayabusa/issues/1480
@fukusuket Do you know how to update the colors in the scan wizard? For example, I want to use 0,255,0 green for selected answers, the brighter blue we use for field data unselected answers, etc...
=> update color scheme

CHANGELOG-Japanese.md, CHANGELOG.md, src/main.rs, src/timeline/metrics.rs
- Closed #1479 
- https://github.com/Yamato-Security/hayabusa/actions/runs/11752599729
=> fix: not output stdout err msg when timestamp parse error in metrics cmd

.github/workflows/integration-test.yml, CHANGELOG-Japanese.md, CHANGELOG.md, contributors.txt, src/detections/configs.rs, src/detections/detection.rs, src/detections/utils.rs, src/main.rs, src/timeline/timelines.rs
- Closed #1491 
https://github.com/Yamato-Security/hayabusa/actions/runs/11853318764
=> feat: output field information in green and messages in orange

CHANGELOG-Japanese.md, CHANGELOG.md, src/detections/rule/base64_match.rs, src/detections/rule/fast_match.rs, src/detections/rule/matchers.rs, src/detections/rule/mod.rs
- Closed #1432 
- Refactoring:
- Separated `FastMatch` and `base64offset` processing because there was too much processing in `mathers.rs`
- https://github.com/Yamato-Security/hayabusa/actions/runs/11977619969
=> feat: `utf16/utf16be/utf16le/wide` modifiers 

src/timeline/search.rs
I've reduced some usage of `clone` in `search.rs`
Before:
```
./hayabusa-2.18.0 search -d ../hayabusa-sample-evtx -r ".*" -o before.csv --debug -C
┏┓ ┏┳━━━┳┓  ┏┳━━━┳━━┓┏┓ ┏┳━━━┳━━━┓
┃┃ ┃┃┏━┓┃┗┓┏┛┃┏━┓┃┏┓┃┃┃ ┃┃┏━┓┃┏━┓┃
┃┗━┛┃┃ ┃┣┓┗┛┏┫┃ ┃┃┗┛┗┫┃ ┃┃┗━━┫┃ ┃┃
┃┏━┓┃┗━┛┃┗┓┏┛┃┗━┛┃┏━┓┃┃ ┃┣━━┓┃┗━┛┃
┃┃ ┃┃┏━┓┃ ┃┃ ┃┏━┓┃┗━┛┃┗━┛┃┗━┛┃┏━┓┃
┗┛ ┗┻┛ ┗┛ ┗┛ ┗┛ ┗┻━━━┻━━━┻━━━┻┛ ┗┛
by Yamato Security
Searching...
Start time: 2024/11/30 09:07
Total event log files: 598
Total file size: 139.2 MB
Currently searching. Please wait.
[00:00:09] 598 / 598 ⠉ [========================================] 100%
Saved results: before.csv (34.9 MB)
Elapsed time: 00:00:08.1258
Analysis Processing Time: 00:00:08.965
Output Processing Time: 00:00:00.287
Memory usage stats:
heap stats:     peak       total       freed     current …
```
=> reduce clone in search.rs

.github/workflows/timeline-diff.yml, CHANGELOG-Japanese.md, CHANGELOG.md, Cargo.lock, Cargo.toml, src/detections/configs.rs, src/detections/utils.rs, src/main.rs, src/timeline/extract_base64.rs, src/timeline/metrics.rs, src/timeline/mod.rs, src/timeline/timelines.rs
- Closed #1512
- https://github.com/Yamato-Security/hayabusa/actions/runs/12106511834
=> feat: `extract-base64` cmd

.github/workflows/timeline-diff.yml, src/main.rs
- Closed #1524 
- This issue only occurs in the dev version.
```
% ./hayabusa
┏┓ ┏┳━━━┳┓  ┏┳━━━┳━━┓┏┓ ┏┳━━━┳━━━┓
┃┃ ┃┃┏━┓┃┗┓┏┛┃┏━┓┃┏┓┃┃┃ ┃┃┏━┓┃┏━┓┃
┃┗━┛┃┃ ┃┣┓┗┛┏┫┃ ┃┃┗┛┗┫┃ ┃┃┗━━┫┃ ┃┃
┃┏━┓┃┗━┛┃┗┓┏┛┃┗━┛┃┏━┓┃┃ ┃┣━━┓┃┗━┛┃
┃┃ ┃┃┏━┓┃ ┃┃ ┃┏━┓┃┗━┛┃┗━┛┃┗━┛┃┏━┓┃
┗┛ ┗┻┛ ┗┛ ┗┛ ┗┛ ┗┻━━━┻━━━┻━━━┻┛ ┗┛
by Yamato Security
Hayabusa v3.0.0 - Dev Build
Yamato Security (https://github.com/Yamato-Security/hayabusa - @SecurityYamato)
Usage:
hayabusa.exe <COMMAND> [OPTIONS]
hayabusa.exe help <COMMAND> or hayabusa.exe <COMMAND> -h
Commands:
computer-metrics     Output the total number of events according to computer names
csv-timeline         Create a DFIR timeline and save it in CSV format
eid-metrics          Output event ID metrics (total number and percent of events, channel, ID, event name)
extract-base64 …
```
=> fix: `update-rules` version check

.github/workflows/integration-test.yml, CHANGELOG-Japanese.md, CHANGELOG.md, src/detections/detection.rs, src/lib.rs, src/yaml.rs, src/yaml_expand.rs
- Closed #1434 
- https://github.com/Yamato-Security/hayabusa/actions/runs/12215234662
=> feat: add support `expand` modifier

CHANGELOG-Japanese.md, CHANGELOG.md, src/detections/configs.rs, src/main.rs
- Closed #1530 
https://github.com/Yamato-Security/hayabusa/actions/runs/12362528975
=> fix: add jsonl to `--JSON-input` target extensions

CHANGELOG-Japanese.md, CHANGELOG.md, src/detections/detection.rs, src/detections/rule/correlation_parser.rs, src/detections/rule/mod.rs
- Closed #1447 
- In addition, I have noticed a bug in the `temporal` rule's  time windows detection logic, which has also been corrected.
https://github.com/Yamato-Security/hayabusa/actions/runs/12445888496
=> Support Ordered Temporal Proximity correlation

src/detections/configs.rs
- Closed #1541  
```
% ./hayabusa csv-timeline --help
Hayabusa v3.0.1 - 3rd Year Anniversary Release
Yamato Security (https://github.com/Yamato-Security/hayabusa - @SecurityYamato)
Usage:
hayabusa.exe csv-timeline <INPUT> [OPTIONS]
Input:
-d, --directory <DIR>  Directory of multiple .evtx files
-f, --file <FILE>      File path to one .evtx file
-l, --live-analysis    Analyze the local C:\Windows\System32\winevt\Logs folder
General Options:
-C, --clobber                        Overwrite files when saving
-h, --help                           Show the help menu
-J, --JSON-input                     Scan JSON formatted logs instead of .evtx (.json or .jsonl)
-w, --no-wizard                      Do not ask questions. Scan for all events and alerts
-Q, --quiet-errors                   Quiet …
```
=> fix: modify csv-timeline help msg

CHANGELOG-Japanese.md, CHANGELOG.md, Cargo.lock, Cargo.toml, src/detections/configs.rs, src/yaml_expand.rs
- Closed #1543 
https://github.com/Yamato-Security/hayabusa/actions/runs/12811214757
=> feat: add timeline-start/timeline-end option to search command 

CHANGELOG-Japanese.md, CHANGELOG.md, src/main.rs
- Closed #1544 
https://github.com/Yamato-Security/hayabusa/actions/runs/12831409129
=> feat: add channel filter to logon-summary

CHANGELOG-Japanese.md, CHANGELOG.md, src/timeline/extract_base64.rs
- Closed #1549 
https://github.com/Yamato-Security/hayabusa/actions/runs/12867115258
=> 1549 add power shell classic eid400 to extract-base64

CHANGELOG-Japanese.md, CHANGELOG.md, src/detections/configs.rs, src/main.rs, src/timeline/metrics.rs, src/timeline/timelines.rs
- Closed #1478 
- https://github.com/Yamato-Security/hayabusa/actions/runs/12927978824
=> feat: add `-X, --remove-duplicate-detections` option to `eid-metrics` and `logon-summary`

CHANGELOG-Japanese.md, CHANGELOG.md, src/afterfact.rs
- Closed #1553 
- https://github.com/Yamato-Security/hayabusa/actions/runs/12949605224
=> fix: not create unnecessary output file in `logon-summary` and `pivot-keywords-list`

src/detections/configs.rs, src/main.rs, src/timeline/search.rs, src/timeline/timelines.rs
- add `sort-events` option to search command
- not to store all the hit records in memory and output them immediately when they are detected if `sort-events` option isn't specified.
@YamatoSecurity 
I checked the following patterns and confirmed that hayabusa output correct results. But I haven't tried a very big windows event file so could you try it?
Also, I'm not falimair with the `search` command so more comments are welcome.
- specify `sort-events` option
- specify no `sort-events` option
=> add "sort-events" option to search command #1475

.gitignore, CHANGELOG-Japanese.md, CHANGELOG.md, Cargo.lock, Cargo.toml, config/html_report/hayabusa_report.css, config/level_color.txt, src/afterfact.rs, src/detections/configs.rs, src/detections/detection.rs, src/detections/message.rs, src/level.rs, src/lib.rs
- Closed #1551 
- added `config/critical_system.txt`  
- Refactor Level conversion logic
-  Level string mapping process is separated in `level.rs`
https://github.com/Yamato-Security/hayabusa/actions/runs/13261188409
=> feat: Level adjusting depending on `config/critical_systems.txt` - "Emergency Alerts"

CHANGELOG-Japanese.md, CHANGELOG.md, config/html_report/hayabusa_report.css, src/afterfact.rs
- Closed #1571 
- Also, Fixed css change omission at the emer level
https://github.com/Yamato-Security/hayabusa/actions/runs/13283636451
=> fix: output rule author in html report

.github/workflows/integration-test.yml, CHANGELOG-Japanese.md, CHANGELOG.md, src/afterfact.rs, src/detections/configs.rs, src/level.rs, src/main.rs, src/timeline/config_critical_systems.rs, src/timeline/mod.rs, src/timeline/timelines.rs, src/yaml.rs, test_files/rules/level_yaml/info.yml
- Closed #1570 
https://github.com/Yamato-Security/hayabusa/actions/runs/13343546597
=> feat: add config-critical-systems cmd

CHANGELOG-Japanese.md, CHANGELOG.md, src/yaml.rs
- Closed #1606 
https://github.com/Yamato-Security/hayabusa/actions/runs/13604232118
=> fix: exclude invalid `expand` rules

.github/workflows/integration-test.yml
- Closed #1597
On Windows, there is a difference in the number of results due to Windows Defender. 
Therefore, compare the number of  `wc -l` only on Ubuntu and macOS.
https://github.com/Yamato-Security/hayabusa/actions/runs/13604064714
(Tests will fail until https://github.com/Yamato-Security/hayabusa/issues/1606  is fixed)
=> test: add `live-response` package result count check in Integration-Test

CHANGELOG-Japanese.md, CHANGELOG.md, src/detections/message.rs
- Closed #1623 
Based on the following specification, modified to output fields in `Details` when `Details` is undefined.
(instead of empty column)
- https://github.com/Yamato-Security/hayabusa/issues/900
- https://github.com/Yamato-Security/hayabusa/actions/runs/13678246350
=> fix: field outputted twice when `Details` does not set

CHANGELOG-Japanese.md, CHANGELOG.md, src/detections/configs.rs, src/timeline/computer_metrics.rs
- Closed #1654 
I have confirmed that the issue has been resolved in the rules_config.txt file in the following PR.
- https://github.com/Yamato-Security/hayabusa-encoded-rules/pull/12
- https://github.com/Yamato-Security/hayabusa/actions/runs/14582730021
=> fix: computer-metrics live-response package

CHANGELOG-Japanese.md, CHANGELOG.md, Cargo.lock, src/detections/detection.rs, src/options/geoip_search.rs, src/options/profile.rs, src/yaml.rs
- Make yaml ruletype field optional
- Related: https://github.com/Yamato-Security/hayabusa/pull/1641
- https://github.com/Yamato-Security/hayabusa/actions/runs/15083650408
=> chg: make yaml ruletype field optional

Cargo.lock, Cargo.toml, src/main.rs
support access System32 dir without redirect, so we can run 32 bit exe on 64 bit os
ref:
- https://learn.microsoft.com/en-us/windows/win32/api/wow64apiset/nf-wow64apiset-wow64disablewow64fsredirection
- https://github.com/Yamato-Security/hayabusa/issues/478
- https://github.com/Yamato-Security/hayabusa/pull/482
=> fix: support access System32 dir without redirect, so we can run 32 bit exe on 64 bit os

Cargo.lock, Cargo.toml
@YamatoSecurity 
Sorry, I just realized that rand is already used in the main dependencies, so the dev-dependency section itself was unnecessary. I also removed crates that weren’t being used.
https://github.com/Yamato-Security/hayabusa/actions/runs/17372540034
=> fix: remove unused dependency
